const employeesData =
    [
        { id: 0, name: "Ramin", family_name: "kheradmand", gender: "male" , phone: "415-555-0163", email: "ramin.kheradmand@example.com" },
        { id: 1, name: "John", family_name: "Doe", gender: "male", phone: "415-555-0164", email: "john.doe@example.com" },
        { id: 2, name: "Jane", family_name: "Doe", gender: "female", phone: "415-555-0165", email: "jane.doe@example.com" },
        { id: 3, name: "Alice", family_name: "Smith", gender: "female", phone: "415-555-0166", email: "alice.smith@example.com" },
        { id: 4, name: "Bob", family_name: "Smith", gender: "male", phone: "415-555-0167", email: "bob.smith@example.com" },
        { id: 5, name: "Emily", family_name: "Brown", gender: "female", phone: "415-555-0168", email: "emily.brown@example.com" },
        { id: 6, name: "Michael", family_name: "Williams", gender: "male", phone: "415-555-0169", email: "michael.williams@example.com" },
        { id: 7, name: "David", family_name: "Jones", gender: "male", phone: "415-555-0170", email: "david.jones@example.com" },
        { id: 8, name: "Emma", family_name: "Wilson", gender: "female", phone: "415-555-0171", email: "emma.wilson@example.com" },
        { id: 9, name: "Olivia", family_name: "Miller", gender: "female", phone: "415-555-0172", email: "olivia.miller@example.com" },
        { id: 10, name: "James", family_name: "Taylor", gender: "male", phone: "415-555-0173", email: "james.taylor@example.com" },
        { id: 11, name: "William", family_name: "Brown", gender: "male", phone: "415-555-0174", email: "william.brown@example.com" },
        { id: 12, name: "Sophia", family_name: "Anderson", gender: "female", phone: "415-555-0175", email: "sophia.anderson@example.com" },
        { id: 13, name: "Charlotte", family_name: "Jackson", gender: "female", phone: "415-555-0176", email: "charlotte.jackson@example.com" },
        { id: 14, name: "Benjamin", family_name: "White", gender: "male", phone: "415-555-0177", email: "benjamin.white@example.com" },
        { id: 15, name: "Lucas", family_name: "Harris", gender: "male", phone: "415-555-0178", email: "lucas.harris@example.com" },
        { id: 16, name: "Mia", family_name: "Martin", gender: "female", phone: "415-555-0179", email: "mia.martin@example.com" },
        { id: 17, name: "Harper", family_name: "Thompson", gender: "female", phone: "415-555-0180", email: "harper.thompson@example.com" },
        { id: 18, name: "Elijah", family_name: "Garcia", gender: "male", phone: "415-555-0181", email: "elijah.garcia@example.com" },
        { id: 19, name: "Alexander", family_name: "Martinez", gender: "male", phone: "415-555-0182", email: "alexander.martinez@example.com" },
        { id: 20, name: "Liam", family_name: "Robinson", gender: "male", phone: "415-555-0183", email: "liam.robinson@example.com" },
        { id: 21, name: "Evelyn", family_name: "Clark", gender: "female", phone: "415-555-0184", email: "evelyn.clark@example.com" },
        { id: 22, name: "Avery", family_name: "Rodriguez", gender: "female", phone: "415-555-0185", email: "avery.rodriguez@example.com" },
        { id: 23, name: "Ella", family_name: "Lewis", gender: "female", phone: "415-555-0186", email: "ella.lewis@example.com" },
        { id: 24, name: "Jackson", family_name: "Lee", gender: "male", phone: "415-555-0187", email: "jackson.lee@example.com" },
        { id: 25, name: "Scarlett", family_name: "Walker", gender: "female", phone: "415-555-0188", email: "scarlett.walker@example.com" },
        { id: 26, name: "Aria", family_name: "Hall", gender: "female", phone: "415-555-0189", email: "aria.hall@example.com" },
        { id: 27, name: "Riley", family_name: "Allen", gender: "male", phone: "415-555-0190", email: "riley.allen@example.com" },
        { id: 28, name: "Mateo", family_name: "Young", gender: "male", phone: "415-555-0191", email: "mateo.young@example.com" },
        { id: 29, name: "Amelia", family_name: "Hernandez", gender: "female", phone: "415-555-0192", email: "amelia.hernandez@example.com" },
        { id: 30, name: "Mason", family_name: "King", gender: "male", phone: "415-555-0193", email: "mason.king@example.com" },
        { id: 31, name: "Luna", family_name: "Wright", gender: "female", phone: "415-555-0194", email: "luna.wright@example.com" },
        { id: 32, name: "Zoey", family_name: "Lopez", gender: "female", phone: "415-555-0195", email: "zoey.lopez@example.com" },
        { id: 33, name: "Ethan", family_name: "Scott", gender: "male", phone: "415-555-0196", email: "ethan.scott@example.com" },
        { id: 34, name: "Logan", family_name: "Green", gender: "male", phone: "415-555-0197", email: "logan.green@example.com" },
        { id: 35, name: "Layla", family_name: "Baker", gender: "female", phone: "415-555-0198", email: "layla.baker@example.com" },
        { id: 36, name: "Sebastian", family_name: "Adams", gender: "male", phone: "415-555-0199", email: "sebastian.adams@example.com" },
        { id: 37, name: "Nora", family_name: "Nelson", gender: "female", phone: "415-555-0200", email: "nora.nelson@example.com" },
        { id: 38, name: "Jack", family_name: "Hill", gender: "male", phone: "415-555-0201", email: "jack.hill@example.com" },
        { id: 39, name: "Aiden", family_name: "Ramirez", gender: "male", phone: "415-555-0202", email: "aiden.ramirez@example.com" }
    ]


export {employeesData}

